version: '3.7'

services:
  web:
    image: barry8000/graph-samm:web-2021-05-01
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - mediafiles:/data/mediafiles:ro
    env_file:
      - ./frontend/pwa/.env.production
    ports:
      - 80:80
      - 443:443
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.db
    restart: always

  api:
    image: barry8000/graph-samm:api-2021-05-01
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    volumes:
      - mediafiles:/mediafiles
    env_file:
      - ./backend/api/.env.prod
    command: "sh ./entrypoint.sh"
    restart: always
      
  tf:
    image: barry8000/graph-samm:ftx-2021-04-22
    build:
       context: ./search-model
       dockerfile: ./Dockerfile.model
    ports:
      - 8501:8501
    restart: always
volumes:
  postgres_data:
  mediafiles: