version: '3.7'

services:

  web:
    image: barry8000/graph-samm:web-dev-latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/pwa:/pwa
    env_file:
      - ./frontend/pwa/.env.development
    ports:
      - 8080:8080
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.db

  api:
    image: barry8000/graph-samm:api-dev-latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/api:/usr/src/app
    env_file:
      - ./backend/api/.env.dev
    ports:
      - 8000:8000
    command: "sh ./entrypoint.sh"
    restart: always
      
  tf:
    image: barry8000/graph-samm:ret-latest
    build:
       context: ./search-model
       dockerfile: ./Dockerfile.model
    ports:
      - 8501:8501
    restart: always
volumes:
  postgres_data: