version: '3.7'

services:

  web:
    image: barry8000/graph-samm:web-2021-04-05
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./frontend/pwa/.env.production
    ports:
      - 8765:80
    restart: always

  # api-nginx:
  #   image: nginx:latest 
  #   ports: 
  #     - 7777:80
  #   volumes:
  #     - './backend/nginx:'

  api:
    image: barry8000/graph-samm:api-2021-04-05
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/api/.env
    ports:
      - 8000:8000
    command: "sh ./entrypoint.sh"
    restart: always
      
  tf:
    image: barry8000/graph-samm:ftx-2021-04-05
    build:
       context: ./search-model
       dockerfile: ./Dockerfile.model
    ports:
      - 8501:8501
    restart: always