# Generated by Django 3.1.2 on 2020-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField()),
                ('detail_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
