# Generated by Django 3.1.2 on 2021-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/tmp', verbose_name='uploaded image'),
        ),
    ]
