# Generated by Django 3.1.2 on 2021-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0003_auto_20210831_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='classification_id',
            field=models.ManyToManyField(blank=True, to='ImageSearch.Classification'),
        ),
    ]
