# Generated by Django 3.1.2 on 2021-08-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0004_auto_20210831_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='created',
            new_name='created_date',
        ),
    ]
