# Generated by Django 3.1.2 on 2021-09-01 08:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0006_auto_20210831_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='when the model was trained')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageSearch.imagemetadata', verbose_name='image that the features are from')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageSearch.featuremodel', verbose_name='model that created the vector')),
            ],
        ),
    ]
