# Generated by Django 3.1.2 on 2021-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0007_featuremodel_imagefeatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFeatures',
            new_name='ImageFeature',
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='query_parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='a json representation of the query filter parameters'),
        ),
    ]
