# Generated by Django 3.1.2 on 2021-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0008_auto_20210916_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='image_fpath',
            field=models.CharField(max_length=300, null=True, verbose_name='local path to image'),
        ),
    ]
