# Generated by Django 3.1.2 on 2021-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0009_imagemetadata_image_fpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='record_id',
            field=models.IntegerField(verbose_name="provider's original object id"),
        ),
    ]
