# Generated by Django 3.1.2 on 2021-12-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0010_auto_20211201_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='image_fpath',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fpath', models.CharField(max_length=300, null=True, verbose_name='local path to image')),
                ('image_metadata_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ImageSearch.imagemetadata')),
            ],
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageSearch.image', verbose_name='image that the features are from'),
        ),
    ]
