# Generated by Django 3.1.2 on 2021-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0011_auto_20211201_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_fpath',
        ),
        migrations.AddField(
            model_name='image',
            name='directory',
            field=models.CharField(max_length=300, null=True, verbose_name='local directory where image is saved'),
        ),
        migrations.AddField(
            model_name='image',
            name='provider_filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='original filename'),
        ),
    ]
