FROM google/tf-serving-scann

# Identify the maintainer of an image
LABEL maintainer="barry.sunderland@librarylab.ethz.ch"

COPY ./models/retrieval/2 /models/retrieval/2
COPY ./models/retrieval_exclusion/2 /models/retrieval_exclusion/2